### ISSUE TITLE
这里好像有点问题

### ISSUE THREAD

**Issue by xiongdun8** [ystemsrx/Qwen2-Boundless#8]
transformers下载并更新到最新版本。把huggingface上面关于模型的文件都下载了，也通过 pip install --upgrade torch命令下载最新的Pytorch库。并访问[英伟达toolkit仓库](https://developer.nvidia.com/cuda-toolkit-archive)下载toolkit12.4.1版本，最后终端运行了

pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124

还是出现报错

报错信息
-------------------------------------------------------------------------------------------------------------------------------------------------

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Qwen2-Boundless-main\continuous_conversation.py", line 10, in <module>
    model = AutoModelForCausalLM.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\python\Lib\site-packages\transformers\models\auto\auto_factory.py", line 564, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\python\Lib\site-packages\transformers\modeling_utils.py", line 3318, in from_pretrained
    raise ImportError(
ImportError: Using `low_cpu_mem_usage=True` or a `device_map` requires Accelerate: `pip install accelerate`
![BaiduShurufa_2024-9-8_21-57-10](https://github.com/user-attachments/assets/aecc81d6-7fa8-4007-8996-c5841bae2228)

**Comment by xiongdun8** [comment]
看漏了报错信息，终端运行
pip install accelerate
得到解决

最后运行时有两条奇怪的提醒
------------------------------------------------------------------------------------------------------------------------------------------
**Assistant**: The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
E:\python\Lib\site-packages\transformers\models\qwen2\modeling_qwen2.py:580: **UserWarning**: 1Torch was not compiled with flash attention. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:555.)
  attn_output = torch.nn.functional.scaled_dot_product_attention(

**Comment by ystemsrx** [comment]
这两个警告没有什么大影响，一个是Attention Mask 没有设置，还有一个是没有编译 Flash Attention，可以不用处理

**Comment by 2572018246** [comment]
我b站私信您了，请问不能直接运行怎么办

![Image](https://github.com/user-attachments/assets/5c64a47f-0324-4b1b-bcfe-4bca1ec819e9)
